FROM caddy:2-alpine

COPY web-frontend/Caddyfile /etc/caddy/Caddyfile
COPY web-frontend/index.html /usr/share/caddy/index.html
COPY web-frontend/styles.css /usr/share/caddy/styles.css
COPY web-frontend/app.js /usr/share/caddy/app.js
COPY web-frontend/ntpp-logo.png /usr/share/caddy/ntpp-logo.png
